name: Build

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Generate .env.production file
      run: echo "${{ secrets.ENV_PRODUCTION }}" > .env.production 

    - name: Install dependencies & Build
      run: |
        npm install
        npm run build

    - name: Upload frontend artifact
      uses: actions/upload-artifact@v4
      with:
        name: auth-client-build
        path: dist/

  copy-to-droplet:

    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Download frontend artifact
      uses: actions/download-artifact@v4
      with:
        name: auth-client-build

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy frontend to Droplet
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ vars.DROPLET_URL }} "mkdir -p /app/auth-client"
        scp -r -o StrictHostKeyChecking=no ./* ${{ secrets.DROPLET_USER }}@${{ vars.DROPLET_URL }}:~/app/auth-client/
  

